FROM apache/airflow:2.8.4
COPY requirements.txt /requirements.txt
COPY clearml.conf /clearml.conf
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /requirements.txt
env CLEARML_WEB_HOST=https://app.clear.ml
env CLEARML_API_HOST=https://api.clear.ml
env CLEARML_FILES_HOST=https://files.clear.ml
env CLEARML_API_ACCESS_KEY=your_access_key
env CLEARML_API_SECRET_KEY=your_api_key